### ISSUE TITLE
Should we add more tags and revise descriptions?

### ISSUE THREAD

**Issue by uyw4687** [line/license-gradle-plugin-git#3]
Gradle plugin portal declares that a forked repository can be rejected.
Since the original repository was not being maintained and our case seems to be an exception case, how about setting different description and tags?

For example, 
1. adding 'git' to the tags
2. Write about git-related functionality on the description

Original : `Applies a header to files, typically a license`
Revised : `Applies a header to files, typically a license. This plugin supports git based configurations.`

**Comment by minwoox** [comment]
Yeah, let's add the tag and fix the description.
We also need to change the `website` and `vcsurl`:
https://github.com/line/license-gradle-plugin-git/blob/main/build.gradle#L116-L117
